### ISSUE TITLE
the code dosent work now throws a exception

### ISSUE THREAD

**Issue by chaudharyjatin115** [ravindravala/Flutter-Reels-downloader-for-instagram#1]
i just tried reading through instagrams apis i think the api is depreceated since oct

**Comment by prannavmaytray** [comment]
i couldn't get this to work either however I did come across another [Instagram reels downloader](https://reelit.io) if you're interested.

**Comment by chaudharyjatin115** [comment]
yeah thanks man ig they need user credentials now

**Comment by ravindravala** [comment]
@chaudharyjatin115 @prannavmaytray  can you provide the error details ?
