### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by DouglasAFerrari** [ravindravala/Flutter-Reels-downloader-for-instagram#2]
Video footage does not load![Screenshot_20220612-115155.png](https://user-images.githubusercontent.com/98489671/173239020-8e7e3429-a21c-461a-9ed4-211e0ab460ea.png)

**Comment by ravindravala** [comment]
@DouglasAFerrari  can you share your flutter version ?

**Comment by DouglasAFerrari** [comment]
Flutter 3.0.2

**Comment by ravindravala** [comment]
Hey @DouglasAFerrari  i updated the packages version as per flutter 3.0.2 , now it'w working
![Screenshot_1655222482](https://user-images.githubusercontent.com/55114723/173623296-a0cbb025-5acf-472d-9c00-5a27acc0a10e.png)
![Screenshot_1655222514](https://user-images.githubusercontent.com/55114723/173623401-400c93bc-fc8f-4a81-bb78-eafcdfa1b795.png)
