### ISSUE TITLE
_TypeError type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by kushaln007** [ravindravala/Flutter-Reels-downloader-for-instagram#3]
I have this kind of error and video is not downloading pls help me @ravindravala .

**Comment by ravindravala** [comment]
Can you please share the steps to reproduce the error @kushaln007  ?

**Comment by kushaln007** [comment]
Yes! ,  select link , paste on textfield and click on download then you get this error.

**Comment by ravindravala** [comment]
@kushaln007 issue fixed in new update
