### ISSUE TITLE
the download is not working

### ISSUE THREAD

**Issue by danchengash** [ravindravala/Flutter-Reels-downloader-for-instagram#5]
it throws exception.

**Comment by ravindravala** [comment]
@Genialngash  can share more details ? Screenshots, your flutter version, build platform, etc

**Comment by danchengash** [comment]
`Future<String?> _startDownload(String link, BuildContext context) async {
    // Asking for video storage permission

    var status = await Permission.storage.status;
    // var runtimePermission = await Permission.

    if (status.isGranted) {
    } else if (status.isRestricted || status.isDenied) {
      await [Permission.storage].request();
    } else {
      log("Permissions permanently denied");
    }
    isLogin = false;
    // Checking for Cookies
    final cookieManager = wb.WebviewCookieManager();
    final gotCookies = await cookieManager.getCookies('https://www.instagram.com/');
    // is Cookie found then set isLogin to true
    if (gotCookies.length > 0) isLogin = true;
    // Build the url
    var linkParts = link.replaceAll(" ", "").split("/");
    var url = '${linkParts[0]}//${linkParts[2]}/${linkParts[3]}/${linkParts[4]}' +
        "?__a=1&__d=dis";

    // Make Http requiest to get the download link of video
    var httpClient = new HttpClient();
    String? videoURLLLLL;
    try {
      var request = await httpClient.getUrl(Uri.parse(url));
      gotCookies.forEach((element) {
        request.cookies.add(Cookie(element.name, element.value));
      });
      var response = await request.close();
      if (response.statusCode == HttpStatus.ok) {
        var json = await response.transform(utf8.decoder).join();
        var data = jsonDecode(json);
        if (isLogin) {
          InstaPostWithLogin postWithLogin = InstaPostWithLogin.fromJson(data);

          videoURLLLLL = postWithLogin.items?.first.videoVersions?.first.url;
        } else {
          InstaPostWithoutLogin post = InstaPostWithoutLogin.fromJson(data);

          videoURLLLLL = post.graphql?.shortcodeMedia?.videoUrl;
        Logger().w(post.toJson());

        }
      }
    } catch (exception) {
      log(exception.toString());
      // Login to instagram in case of Cookie expire or download any private account's video
      await Navigator.push(context, MaterialPageRoute(builder: (_) => InstaLogin()));
    }

    // Download video & save
    if (videoURLLLLL == null) {

      return null;
    } else {
      var appDocDir = await getTemporaryDirectory();
      String savePath = appDocDir.path + "/temp.mp4";
      await dio.download(videoURLLLLL, savePath);
      final result = await ImageGallerySaver.saveFile(savePath, isReturnPathOfIOS: true);
      print(result);
      return result["filePath"];
    }
  }`

the above code is the one throwing an exception.
when i try to print/log the **videoURLLLLL**  its returned as null

**Comment by ravindravala** [comment]
@Genialngash there are some limitations in the code 

- insta login required to download private reels and also if you exceed the free quota of insta API

- at now you can't able to download video if there is multiple video in post
