### ISSUE TITLE
getTemporaryDirectory() error:

### ISSUE THREAD

**Issue by BobbyDahal** [ravindravala/Flutter-Reels-downloader-for-instagram#7]
In thedownloadcontroller.dart there is a error in gettemporarydirectory.
[{
	"resource": "/c:/Users/bobby/Desktop/videodownloader/lib/Controller/DownloadController.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getTemporaryDirectory' isn't defined for the type 'DownloadController'.\nTry correcting the name to the name of an existing method, or defining a method named 'getTemporaryDirectory'.",
	"source": "dart",
	"startLineNumber": 65,
	"startColumn": 29,
	"endLineNumber": 65,
	"endColumn": 50
}]
Help

**Comment by ravindravala** [comment]
Resolved
